### ISSUE TITLE
re-implement for writer verification

### ISSUE THREAD

**Issue by pastaxingxin** [hrantzsch/signature-verification#10]
hello，I am reading your paper "Signature Emb e dding: Writer Indep ende nt Offline Signature Verification
with Deep Metric Learning"
Recently，I need to use your model in my paper.However, your code is too difficult for me to learn, not even re-implement.
Could you please improve your code and make annotations？
Thank you in advance。

**Comment by hrantzsch** [comment]
Hi,
sorry for the late response, I'll be happy to help to understand what I did. In fact, I have already started to re-write the code in a more structured way.
Please take a look at [this repository](https://github.com/hrantzsch/signature-embedding). I didn't finish it yet and probably won't have the time to do so in the near future. However, all the basic components are there. You just need to ajdust the code to work on actual signature data.
Feel free to open another issue in the other repository if anything is unclear to you.
